### ISSUE TITLE
有些问题，我也在借鉴您的代码

### ISSUE THREAD

**Issue by awesomehhhhh** [cjyx9/YoxueHelper#1]
[我的demo](https://github.com/awesomehhhhh/ebagqbot/blob/master/python/webyxp.py) 
我在您的脚本里面发现了一些问题
1 获取答案，有些题是题里面套题，就是recordset-lists里面还有一个lists
2 班级id，这在某些人里面有两个
3获取没写的作业，这可以使用更简单的api实现，但无法获得具体的信息：
http://api2.anoah.com/jwt/homework/publish/getUndoNumForStudent?user_id=%s&class_id=%s&from_date=&to_date=
我写的Python可以说是屎山了，同时还需要把这个东西集成到QQ机器人上面。

**Comment by cjyx9** [comment]
我看看你的代码先😂

**Comment by awesomehhhhh** [comment]
而且还有 一个题里面多个course_resource的，这个通过“course_resource_count”可以判断

**Comment by awesomehhhhh** [comment]
[微不足道的我的命令帮助](https://github.com/awesomehhhhh/ebagqbot/blob/master/README.md)

**Comment by cjyx9** [comment]
https://github.com/cjyx9/FakeAnoah
我把修改的代码放这儿了
你看看吧

**Comment by awesomehhhhh** [comment]
现在就是他作业有这些种类：
1.最简单：作业下第一个项目就是题，需要for1
2.作业下有好多项目，需要for1+for2
3.作业内有不是 互动试题的项目，需要排除（if1）
4.作业内有大题里面套小题的，需要for1+for2+for3
5.有返回[]的，需要删除 test:（if1+if2）
6.有好多项目里面大题套小题的，需要for1+for2+for3+for4

**Comment by awesomehhhhh** [comment]
我也更新了一下脚本，至于is_pydroid其实我方便我在手机运行脚本您可以选择加或者不加

**Comment by cjyx9** [comment]
嗯，我吃完饭后再看看，当时写的时候没想到有人会看，没有在意这些细节

**Comment by cjyx9** [comment]
http://static.anoah.com/uploads/ebag_data/apk/112/33674/_ebag4_200727.apk
这儿有一个平板的智慧课堂安装包，你可以在模拟器上运行一下试试，用Httpcanary抓一下答案解析的api

**Comment by awesomehhhhh** [comment]
我在e.anoah.com和手机上安装了优学派然后在fiddler和packet capture进行抓包，可能是因为Android5.1的原因不需要ROOT

**Comment by awesomehhhhh** [comment]
我在e.anoah.com和手机上安装了yxp
然后在fiddler和packet capture进行抓包，可能是因为Android5.1的原因不需要ROOT

**Comment by awesomehhhhh** [comment]
作业的大概情况，我是通过：
yxpAs 1585745 英语1
yxpAs 1585745 英语2
yxpAs 1585745 英语3
yxpAs 1585745 英语4
yxpAs 1585745 英语5
yxpAs 1585745 英语6
发现的

**Comment by cjyx9** [comment]
我先把issue关了(′⌄‵)

**Comment by awesomehhhhh** [comment]
主要是当初像搜搜看有没有也yxp爬虫的然后就找到了这里😂
